export const products = [
    {
      _id: 1,
      image: "/images/dress1.jpg",
      title: "dress1",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["L", "XL", "XXL"],
      price: 29.9,
      count: 1,
    },
    {
      _id: 2,
      image: "/images/dress2.jpg",
      title: "dress2",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["M", "L"],
      price: 18.9,
      count: 1,
    },
    {
      _id: 3,
      image: "/images/dress3.jpg",
      title: "dress3",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["M", "L"],
      price: 14.9,
      count: 1,
    },
    {
      _id: 4,
      image: "/images/dress4.jpg",
      title: "dress4",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["XL"],
      price: 25.9,
      count: 1,
    },
    {
      _id: 5,
      image: "/images/dress5.jpg",
      title: "dress5",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["L", "XL"],
      price: 10.9,
      count: 1,
    },
    {
      _id: 6,
      image: "/images/dress6.jpg",
      title: "dress6",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["XL", "XXL"],
      price: 49.9,
      count: 1,
    },
    {
      _id: 7,
      image: "/images/dress7.jpg",
      title: "dress7",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["XL", "XXL"],
      price: 49.9,
      count: 1,
    }, 
    {
      _id: 8,
      image: "/images/dress8.jpg",
      title: "dress8",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["XL", "XXL"],
      price: 49.9,
      count: 1,
    },
    {
      _id: 9,
      image: "/images/dress9.jpg",
      title: "dress9",
      description: "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Exclusive to ASOS, our universal brand is here for you, and comes in all our fit ranges: ASOS Curve, Tall, Petite and Maternity. Created by us, styled by you.",
      availableSizes: ["XL", "XXL"],
      price: 49.9,
      count: 1,
    }
]


